-- EP05 B-EP05.10: generalize the idempotent (workspace_id, source_system, source_id)
-- capture key to person/organization/deal. activity (uq_activity_source, 000003/000014) and
-- lead (uq_lead_source, 000008) already have theirs — do NOT recreate those.
-- Also widen audit_log CHECKs so the capture chokepoint (B-EP05.2) can record
-- actor_type='connector' / action='capture'.
BEGIN;

ALTER TABLE person       ADD COLUMN IF NOT EXISTS source_system text NULL;
ALTER TABLE person       ADD COLUMN IF NOT EXISTS source_id     text NULL;
ALTER TABLE organization ADD COLUMN IF NOT EXISTS source_system text NULL;
ALTER TABLE organization ADD COLUMN IF NOT EXISTS source_id     text NULL;
ALTER TABLE deal         ADD COLUMN IF NOT EXISTS source_system text NULL;
ALTER TABLE deal         ADD COLUMN IF NOT EXISTS source_id     text NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_person_source
  ON person (workspace_id, source_system, source_id)
  WHERE source_system IS NOT NULL AND source_id IS NOT NULL AND archived_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_source
  ON organization (workspace_id, source_system, source_id)
  WHERE source_system IS NOT NULL AND source_id IS NOT NULL AND archived_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_deal_source
  ON deal (workspace_id, source_system, source_id)
  WHERE source_system IS NOT NULL AND source_id IS NOT NULL AND archived_at IS NULL;

-- Widen audit_log CHECKs to admit capture-chokepoint writes.
-- Constraint names are auto-generated by Postgres from the inline CHECK in 000003:
-- audit_log_actor_type_check / audit_log_action_check.
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_actor_type_check;
ALTER TABLE audit_log ADD  CONSTRAINT audit_log_actor_type_check
  CHECK (actor_type IN ('human','agent','system','connector'));
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check;
ALTER TABLE audit_log ADD  CONSTRAINT audit_log_action_check
  CHECK (action IN ('create','update','archive','merge','promote','restore',
                    'export','erase','login','assign','advance_stage','capture'));

COMMIT;
