package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
	"unicode"
)

var objectNameRe = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)

func genObject(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crm gen object <Name>")
	}
	name := args[0]
	if !objectNameRe.MatchString(name) {
		return fmt.Errorf("name must be PascalCase (e.g. InvoiceItem)")
	}
	snake := toSnake(name)
	seq, err := nextSeq("backend/migrations")
	if err != nil {
		return err
	}

	// 1. migration pair
	upTmpl := template.Must(template.New("up").Parse(objectUpSQL))
	downTmpl := template.Must(template.New("dn").Parse(objectDownSQL))
	data := map[string]string{tmplKeyName: name, tmplKeySnake: snake}
	if err := renderTmpl(filepath.Join("backend/migrations", seq+"_add_custom_"+snake+".up.sql"), upTmpl, data); err != nil {
		return err
	}
	if err := renderTmpl(filepath.Join("backend/migrations", seq+"_add_custom_"+snake+".down.sql"), downTmpl, data); err != nil {
		return err
	}

	// 2. Go struct + 3. test stub
	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	dir := filepath.Join("backend/internal/modules/directory/custom", snake)
	if err := os.MkdirAll(dir, dirPerm); err != nil {
		return err
	}
	goTmpl := template.Must(template.New("go").Parse(objectGoSrc))
	if err := renderTmpl(filepath.Join(dir, snake+".go"), goTmpl, data); err != nil {
		return err
	}
	testTmpl := template.Must(template.New("test").Parse(objectTestSrc))
	if err := renderTmpl(filepath.Join(dir, snake+"_test.go"), testTmpl, data); err != nil {
		return err
	}

	printSummary(fmt.Sprintf("✓ crm gen object %s\n  migration: backend/migrations/%s_add_custom_%s.{up,down}.sql\n  domain:    backend/internal/modules/directory/custom/%s/\n\nNext steps:\n  make migrate-up && make check\n", name, seq, snake, snake))
	return nil
}

func toSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

const objectUpSQL = `-- Code generated by crm gen object; DO NOT EDIT.
-- Custom object: x_{{.Snake}} (source-customization, ADR-0002/ADR-0017)
CREATE TABLE x_{{.Snake}} (
  id            uuid PRIMARY KEY DEFAULT uuidv7(),
  workspace_id  uuid NOT NULL REFERENCES workspace(id) ON DELETE RESTRICT,
  version       bigint NOT NULL DEFAULT 1,
  source        text NOT NULL,
  captured_by   text NOT NULL,
  raw           jsonb NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  archived_at   timestamptz NULL
);
CREATE INDEX idx_x_{{.Snake}}_ws_live ON x_{{.Snake}} (workspace_id) WHERE archived_at IS NULL;
CREATE TRIGGER trg_x_{{.Snake}}_touch BEFORE UPDATE ON x_{{.Snake}}
  FOR EACH ROW EXECUTE FUNCTION touch_versioned();
ALTER TABLE x_{{.Snake}} ENABLE ROW LEVEL SECURITY;
ALTER TABLE x_{{.Snake}} FORCE ROW LEVEL SECURITY;
CREATE POLICY x_{{.Snake}}_tenant_isolation ON x_{{.Snake}}
  USING      (workspace_id = nullif(current_setting('app.workspace_id', true), '')::uuid)
  WITH CHECK (workspace_id = nullif(current_setting('app.workspace_id', true), '')::uuid);
`

const objectDownSQL = `-- Code generated by crm gen object; DO NOT EDIT.
DROP TABLE IF EXISTS x_{{.Snake}};
`

const objectGoSrc = `// Code generated by crm gen object; DO NOT EDIT.
package {{.Snake}}

// scaffold conventions to be redefined with Phase 2 docs/recipes.
import "github.com/gradionhq/margince/backend/internal/ids"

// {{.Name}} is a custom CRM object (source-customization, ADR-0002).
type {{.Name}} struct {
	ID          string
	WorkspaceID string
	Source      string
	CapturedBy  string
}

// New{{.Name}} creates a {{.Name}} with a fresh UUIDv7 id.
func New{{.Name}}() {{.Name}} { return {{.Name}}{ID: ids.New()} }
`

const objectTestSrc = `// Code generated by crm gen object; DO NOT EDIT.
package {{.Snake}}

import "testing"

func TestNew{{.Name}}_HasID(t *testing.T) {
	o := New{{.Name}}()
	if o.ID == "" {
		t.Fatal("expected non-empty ID")
	}
}

func TestNew{{.Name}}_StructCompleteness(t *testing.T) {
	o := New{{.Name}}()
	_ = o.ID
	_ = o.WorkspaceID
	_ = o.Source
	_ = o.CapturedBy
}
`
