package main

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"
)

func genWorkflow(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crm gen workflow <name>")
	}
	name := args[0]
	if !identRe.MatchString(name) {
		return fmt.Errorf("name must be snake_case (e.g. deal_stalled)")
	}
	dir := filepath.Join("crm", "crm-capture", "workflows")
	data := map[string]string{tmplKeyName: toPascal(name), tmplKeySnake: name}
	files := []scaffold{
		{name + ".go", template.Must(template.New("wf").Parse(workflowGoSrc))},
		{name + "_test.go", template.Must(template.New("wftest").Parse(workflowTestSrc))},
	}
	summary := fmt.Sprintf("✓ crm gen workflow %s\n  handler: %s/%s.go\n  test:    %s/%s_test.go\n\nNext steps:\n  Implement Match/Plan, then: make check\n", name, dir, name, dir, name)
	return emitPair(dir, data, files, summary)
}

// toPascal converts a snake_case string to PascalCase.
func toPascal(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

const workflowGoSrc = `// Code generated by crm gen workflow; DO NOT EDIT.
package workflows

import (
	"context"

	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	"github.com/gradionhq/margince/backend/internal/workflow"
)

// {{.Name}}Handler handles the {{.Snake}}.triggered event.
type {{.Name}}Handler struct{}

func init() { workflow.Register(&{{.Name}}Handler{}) }

func (*{{.Name}}Handler) Match(event string) bool {
	return event == "{{.Snake}}.triggered"
}

func (*{{.Name}}Handler) Plan(ctx context.Context, event string, payload any) error {
	return nil
}
`

const workflowTestSrc = `// Code generated by crm gen workflow; DO NOT EDIT.
package workflows

import "testing"

func Test{{.Name}}Handler_Match(t *testing.T) {
	h := &{{.Name}}Handler{}
	if !h.Match("{{.Snake}}.triggered") {
		t.Errorf("expected Match(%q) == true", "{{.Snake}}.triggered")
	}
	if h.Match("other.event") {
		t.Errorf("expected Match(%q) == false", "other.event")
	}
}
`
