package main

import (
	"fmt"
	"path/filepath"
	"text/template"
)

func genReport(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crm gen report <name>")
	}
	name := args[0]
	if !identRe.MatchString(name) {
		return fmt.Errorf("name must be snake_case (e.g. pipeline_velocity)")
	}
	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	dir := filepath.Join("backend", "internal", "modules", "directory", "reports")
	data := map[string]string{tmplKeyName: goFieldName(name), tmplKeySnake: name}
	files := []scaffold{
		{name + ".go", template.Must(template.New("go").Parse(reportGoSrc))},
		{name + "_test.go", template.Must(template.New("test").Parse(reportTestSrc))},
	}
	summary := fmt.Sprintf("✓ crm gen report %s\n  report: backend/internal/modules/directory/reports/%s.go\n  test:   backend/internal/modules/directory/reports/%s_test.go\n\nNext steps:\n  Fill in the Run implementation, then make check\n", name, name, name)
	return emitPair(dir, data, files, summary)
}

const reportGoSrc = `// Code generated by crm gen report; DO NOT EDIT.
package reports

import "context"

// {{.Name}}Report is a read-only compiled report query.
type {{.Name}}Report struct{}

// Run executes the report and returns rows.
func (*{{.Name}}Report) Run(ctx context.Context) ([]map[string]any, error) {
	return nil, nil
}
`

const reportTestSrc = `// Code generated by crm gen report; DO NOT EDIT.
package reports

import (
	"context"
	"testing"
)

func Test{{.Name}}Report_Run(t *testing.T) {
	r := &{{.Name}}Report{}
	_, err := r.Run(context.Background())
	if err != nil {
		t.Fatalf("Run returned unexpected error: %v", err)
	}
}
`
