package main

import (
	"fmt"
	"path/filepath"
	"text/template"
)

func genTool(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crm gen tool <name>")
	}
	name := args[0]
	if !identRe.MatchString(name) {
		return fmt.Errorf("name must be snake_case (e.g. search_contacts)")
	}
	dir := filepath.Join("crm", "crm-agents", "tools")
	data := map[string]string{tmplKeyName: toPascal(name), tmplKeySnake: name}
	files := []scaffold{
		{name + ".go", template.Must(template.New("tool").Parse(toolGoSrc))},
		{name + "_test.go", template.Must(template.New("tooltest").Parse(toolTestSrc))},
	}
	summary := fmt.Sprintf("✓ crm gen tool %s\n  tool: %s/%s.go\n  test: %s/%s_test.go\n\nNext steps:\n  Implement Invoke, then: make check\n", name, dir, name, dir, name)
	return emitPair(dir, data, files, summary)
}

const toolGoSrc = `// Code generated by crm gen tool; DO NOT EDIT.
package tools

import (
	"context"

	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	"github.com/gradionhq/margince/backend/internal/mcp"
)

// {{.Name}}Tool is a governed MCP tool (default tier: Green).
type {{.Name}}Tool struct{}

func init() { mcp.Register(&{{.Name}}Tool{}) }

func (*{{.Name}}Tool) Name() string   { return "{{.Snake}}" }
func (*{{.Name}}Tool) Tier() mcp.Tier { return mcp.Green }
func (*{{.Name}}Tool) Invoke(_ context.Context, _ []byte) ([]byte, error) {
	return []byte(` + "`" + `{"ok":true}` + "`" + `), nil
}
`

const toolTestSrc = `// Code generated by crm gen tool; DO NOT EDIT.
package tools

import (
	"context"
	"encoding/json"
	"testing"

	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	"github.com/gradionhq/margince/backend/internal/mcp"
)

func Test{{.Name}}Tool_Name(t *testing.T) {
	tool := &{{.Name}}Tool{}
	if got := tool.Name(); got != "{{.Snake}}" {
		t.Errorf("Name() = %q, want %q", got, "{{.Snake}}")
	}
}

func Test{{.Name}}Tool_Tier(t *testing.T) {
	tool := &{{.Name}}Tool{}
	if got := tool.Tier(); got != mcp.Green {
		t.Errorf("Tier() = %v, want mcp.Green", got)
	}
}

func Test{{.Name}}Tool_Invoke(t *testing.T) {
	tool := &{{.Name}}Tool{}
	out, err := tool.Invoke(context.Background(), []byte("{}"))
	if err != nil {
		t.Fatalf("Invoke() unexpected error: %v", err)
	}
	var m map[string]any
	if err := json.Unmarshal(out, &m); err != nil {
		t.Fatalf("Invoke() returned invalid JSON: %v", err)
	}
}
`
