package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	crmYAMLPath  = "backend/api/crm.yaml"
	toolsGenPath = "backend/internal/shared/ports/mcp/tools_gen.go"
)

// mcpToolEntry is one `x-mcp-tool` annotation extracted from crm.yaml — the
// generator's own intermediate shape. It is distinct from mcp.GeneratedTool
// (the hand-written struct the rendered Go literal targets): this package
// never imports the backend module, it only emits Go source text.
type mcpToolEntry struct {
	OperationID string
	Verb        string
	RecordType  string
	Tier        string // "green" | "yellow" | "dynamic"
	Resolver    string
}

var httpMethods = map[string]bool{
	"get": true, "put": true, "post": true, "delete": true,
	"options": true, "head": true, "patch": true, "trace": true,
}

func genMCPTools(_ []string) error {
	spec, err := os.ReadFile(crmYAMLPath)
	if err != nil {
		return fmt.Errorf("read %s: %w (run from the repo root)", crmYAMLPath, err)
	}
	tools, err := parseMCPTools(spec)
	if err != nil {
		return err
	}
	out, err := renderMCPToolsGo(tools)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(toolsGenPath), dirPerm); err != nil {
		return err
	}
	if err := os.WriteFile(toolsGenPath, out, filePerm); err != nil {
		return err
	}
	printSummary(fmt.Sprintf("✓ wrote %s (%d MCP tools)\n", toolsGenPath, len(tools)))
	return nil
}

// parseMCPTools walks every paths.<path>.<method> operation in an OpenAPI
// spec and extracts its `x-mcp-tool` extension, if present. It parses a real
// YAML document (gopkg.in/yaml.v3) rather than regexing the raw text, so a
// commented-out or prose mention of `x-mcp-tool:` never masquerades as a
// tool — only an actual mapping key under an operation counts.
func parseMCPTools(spec []byte) ([]mcpToolEntry, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(spec, &doc); err != nil {
		return nil, fmt.Errorf("parse crm.yaml: %w", err)
	}
	paths, _ := doc["paths"].(map[string]any)

	var tools []mcpToolEntry
	for _, pathItemRaw := range paths {
		pathItem, ok := pathItemRaw.(map[string]any)
		if !ok {
			continue
		}
		for method, opRaw := range pathItem {
			if !httpMethods[strings.ToLower(method)] {
				continue
			}
			op, ok := opRaw.(map[string]any)
			if !ok {
				continue
			}
			xRaw, ok := op["x-mcp-tool"]
			if !ok {
				continue
			}
			x, ok := xRaw.(map[string]any)
			if !ok {
				continue
			}
			opID, _ := op["operationId"].(string)
			if opID == "" {
				return nil, fmt.Errorf("x-mcp-tool annotation (verb=%s) on an operation with no operationId", yamlStr(x["verb"]))
			}
			tools = append(tools, mcpToolEntry{
				OperationID: opID,
				Verb:        yamlStr(x["verb"]),
				RecordType:  yamlStr(x["record_type"]),
				Tier:        yamlStr(x["tier"]),
				Resolver:    yamlStr(x["tier_resolver"]),
			})
		}
	}

	sort.Slice(tools, func(i, j int) bool { return tools[i].OperationID < tools[j].OperationID })
	return tools, nil
}

func yamlStr(v any) string {
	s, _ := v.(string)
	return s
}

// tierConst maps an `x-mcp-tool.tier` string to the mcp.RiskTier identifier
// name (unqualified: tools_gen.go is itself `package mcp`).
func tierConst(tier string) (string, error) {
	switch tier {
	case "green":
		return "TierGreen", nil
	case "yellow":
		return "TierYellow", nil
	case "dynamic":
		return "TierDynamic", nil
	default:
		return "", fmt.Errorf("unknown x-mcp-tool tier %q", tier)
	}
}

// renderMCPToolsGo renders the generated Go source for tools. tools must
// already be in a deterministic order (parseMCPTools sorts by OperationID) —
// this function does no further sorting, so calling it twice on the same
// sorted slice always yields byte-identical output (the gen-mcp-tools-check
// idempotency bar).
func renderMCPToolsGo(tools []mcpToolEntry) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by crm-gen mcp-tools; DO NOT EDIT.\npackage mcp\n\nvar GeneratedTools = []GeneratedTool{\n")
	for _, t := range tools {
		tier, err := tierConst(t.Tier)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", t.OperationID, err)
		}
		fmt.Fprintf(&b, "\t{OperationID: %q, Verb: %q, RecordType: %q, Tier: %s, Resolver: %q},\n",
			t.OperationID, t.Verb, t.RecordType, tier, t.Resolver)
	}
	b.WriteString("}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated mcp tools: %w", err)
	}
	return out, nil
}
