package main

import (
	"fmt"
	"path/filepath"
	"text/template"
)

func genConnector(args []string, baseDir ...string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crm gen connector <name>")
	}
	name := args[0]
	if !identRe.MatchString(name) {
		return fmt.Errorf("name must be snake_case (e.g. gmail)")
	}
	root := "."
	if len(baseDir) > 0 && baseDir[0] != "" {
		root = baseDir[0]
	}
	dir := filepath.Join(root, "crm", "crm-capture", "connectors")
	data := map[string]string{tmplKeyName: toPascal(name), tmplKeySnake: name}
	files := []scaffold{
		{name + ".go", template.Must(template.New("conn").Parse(connectorGoSrc))},
		{name + "_test.go", template.Must(template.New("conntest").Parse(connectorTestSrc))},
	}
	summary := fmt.Sprintf("✓ crm gen connector %s\n  connector: %s/%s.go\n  test:      %s/%s_test.go\n\nNext steps:\n  Implement Normalize, then: make check\n", name, dir, name, dir, name)
	return emitPair(dir, data, files, summary)
}

const connectorGoSrc = `// Code generated by crm gen connector; DO NOT EDIT.
package connectors

import (
	"context"

	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	"github.com/gradionhq/margince/backend/internal/connector"
)

// {{.Name}}Connector normalizes raw bytes from the {{.Snake}} source.
type {{.Name}}Connector struct{}

func init() { connector.Register(&{{.Name}}Connector{}) }

func (*{{.Name}}Connector) Descriptor() connector.Descriptor {
	return connector.Descriptor{Name: "{{.Snake}}", Scopes: []string{"read"}, Tier: "yellow"}
}

func (*{{.Name}}Connector) Normalize(context.Context, []byte) ([]connector.NormalizedRecord, error) {
	return nil, connector.ErrSkip
}
`

const connectorTestSrc = `// Code generated by crm gen connector; DO NOT EDIT.
package connectors

import (
	"context"
	"errors"
	"testing"

	// scaffold conventions to be redefined with Phase 2 docs/recipes.
	"github.com/gradionhq/margince/backend/internal/connector"
)

func Test{{.Name}}Connector_Descriptor(t *testing.T) {
	c := &{{.Name}}Connector{}
	d := c.Descriptor()
	if d.Name != "{{.Snake}}" {
		t.Errorf("Descriptor().Name = %q, want %q", d.Name, "{{.Snake}}")
	}
}

func Test{{.Name}}Connector_Normalize(t *testing.T) {
	c := &{{.Name}}Connector{}
	_, err := c.Normalize(context.Background(), []byte("{}"))
	if !errors.Is(err, connector.ErrSkip) {
		t.Errorf("Normalize() expected ErrSkip, got %v", err)
	}
}
`
