package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const manifestModulePrefix = "github.com/gradionhq/margince/crm"

func genManifests(_ []string) (err error) {
	scanDirs := []string{
		"crm/crm-capture/connectors",
		"crm/crm-capture/workflows",
		"crm/crm-agents/tools",
	}
	pkgs := map[string]bool{}
	fset := token.NewFileSet()
	for _, dir := range scanDirs {
		entries, _ := os.ReadDir(dir)
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
				continue
			}
			f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
			if err != nil || f == nil {
				continue
			}
			// dir is "crm/crm-capture/connectors"; strip leading "crm/" to get the sub-path
			subPath := strings.TrimPrefix(dir, "crm/")
			pkgs[manifestModulePrefix+"/"+subPath] = true
		}
	}
	paths := make([]string, 0, len(pkgs))
	for p := range pkgs {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	tmpl := template.Must(template.New("m").Parse(manifestTmpl))
	out, err := os.Create("backend/cmd/api/imports_gen.go")
	if err != nil {
		return err
	}
	defer func() {
		if cErr := out.Close(); cErr != nil && err == nil {
			err = cErr
		}
	}()
	if err := tmpl.Execute(out, paths); err != nil {
		return err
	}
	printSummary("✓ wrote backend/cmd/api/imports_gen.go\n")
	return nil
}

const manifestTmpl = `// Code generated by crm gen manifests; DO NOT EDIT.
package main
{{if .}}
import (
{{range .}}	_ "{{.}}"
{{end}})
{{end}}`
