#!/usr/bin/env bash
# archive-swarm-logs.sh — bundle swarm + supervisor run logs and the config that
# drove them into a single zip for offline, cross-machine analysis.
#
# Purpose: ship one self-contained archive to another machine to deep-analyze what
# the supervisor + swarm actually did (raw transcripts) against what they were told
# to do (configs, agent prompts, backlog) — to drive improvements to both.
#
# Output: ./.tmp/swarm-analysis-<UTC-timestamp>.zip  (.tmp is gitignored)
#
# Usage:
#   scripts/archive-swarm-logs.sh            # bundle everything
#   OUT_DIR=/some/where scripts/archive-swarm-logs.sh
set -euo pipefail

# --- locate repo root (script lives in <repo>/scripts) ---------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

command -v zip >/dev/null 2>&1 || { echo "error: 'zip' not found on PATH" >&2; exit 1; }

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="${OUT_DIR:-$REPO_ROOT/.tmp}"
ZIP_PATH="$OUT_DIR/swarm-analysis-$STAMP.zip"
mkdir -p "$OUT_DIR"

# Stage into a temp dir OUTSIDE .tmp so we never recurse into our own output and
# so git-tracked configs are snapshotted at their current on-disk state.
STAGE="$(mktemp -d "${TMPDIR:-/tmp}/swarm-analysis.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT
ROOT="$STAGE/swarm-analysis-$STAMP"
mkdir -p "$ROOT"/{logs,config,backlog,reports}

echo "==> Staging run logs (raw evidence)…"
# rsync keeps it cheap and resilient to missing dirs; copy what exists.
copy_dir() { # <src> <dest>
  [ -d "$1" ] || { echo "    (skip, absent) $1"; return; }
  rsync -a --quiet "$1/" "$2/"
  echo "    + $1"
}
copy_dir ".tmp/swarm-supervisor" "$ROOT/logs/swarm-supervisor"
copy_dir ".tmp/swarm"            "$ROOT/logs/swarm"
copy_dir ".tmp/swarm-runs"       "$ROOT/logs/swarm-runs"

echo "==> Staging config / inputs that drove the runs…"
copy_file() { # <src> <dest>
  [ -f "$1" ] || { echo "    (skip, absent) $1"; return; }
  mkdir -p "$(dirname "$2")"
  cp "$1" "$2"
  echo "    + $1"
}
copy_file ".ai/swarm.config.json"  "$ROOT/config/swarm.config.json"
copy_file ".ai/swarm/tunables.md"  "$ROOT/config/swarm-tunables.md"
copy_file "config/ai-routing.yaml" "$ROOT/config/ai-routing.yaml"
copy_file "AGENTS.md"              "$ROOT/config/AGENTS.md"
copy_file "CLAUDE.md"             "$ROOT/config/CLAUDE.md"
copy_dir  ".ai/agents"            "$ROOT/config/agents"
copy_dir  ".ai/checklist"        "$ROOT/config/checklist"
copy_dir  ".ai/skills"           "$ROOT/config/skills"

echo "==> Staging backlog (what the loop consumed)…"
copy_file "swarm/superpowers/backlog/reality.json" "$ROOT/backlog/reality.json"
copy_file "swarm/superpowers/backlog/cooked.json"  "$ROOT/backlog/cooked.json"
copy_file "swarm/superpowers/backlog/README.md"    "$ROOT/backlog/README.md"

echo "==> Staging prior swarm/supervisor reports…"
if [ -d swarm/reports ]; then
  find swarm/reports -maxdepth 1 -type d \( -iname '*swarm*' -o -iname '*supervisor*' -o -iname '*overnight*' \) | while IFS= read -r d; do
    base="$(basename "$d")"
    rsync -a --quiet "$d/" "$ROOT/reports/$base/"
    echo "    + $d"
  done
fi

echo "==> Capturing git context…"
{
  echo "# Git context — captured $STAMP"
  echo
  echo "## HEAD"
  git rev-parse HEAD 2>/dev/null || true
  echo
  echo "## Branch"
  git rev-parse --abbrev-ref HEAD 2>/dev/null || true
  echo
  echo "## Status (porcelain)"
  git status --porcelain 2>/dev/null || true
  echo
  echo "## Recent log (100)"
  git log --oneline -100 2>/dev/null || true
} > "$ROOT/GIT-CONTEXT.md"

echo "==> Writing manifest…"
{
  echo "# Swarm analysis bundle — $STAMP"
  echo
  echo "Generated by scripts/archive-swarm-logs.sh on $(uname -srm)."
  echo
  echo "## Layout"
  echo '```'
  echo "logs/swarm-supervisor/  supervisor heartbeat.log + per-iteration iter-*.jsonl transcripts"
  echo "logs/swarm/             per-dispatch run dirs (session.jsonl, status.json, summary.md, task.md)"
  echo "logs/swarm-runs/        per-epic run artifacts (pr-body.md, tasks/*/task.md)"
  echo "config/                 swarm.config.json, swarm-tunables.md, ai-routing.yaml, agent prompts, AGENTS.md"
  echo "backlog/                reality.json + cooked.json — the backlog the loop consumed"
  echo "reports/                prior swarm/supervisor retrospectives"
  echo "GIT-CONTEXT.md          HEAD, branch, status, recent commits"
  echo '```'
  echo
  echo "## Inventory (file counts by directory)"
  echo '```'
  ( cd "$ROOT" && find logs config backlog reports -type f 2>/dev/null \
      | sed 's#/[^/]*$##' | sort | uniq -c | sort -rn )
  echo '```'
  echo
  echo "## File-type totals"
  echo '```'
  ( cd "$ROOT" && find . -type f | sed 's/.*\.//' | sort | uniq -c | sort -rn )
  echo '```'
} > "$ROOT/MANIFEST.md"

echo "==> Compressing → $ZIP_PATH"
( cd "$STAGE" && zip -rq "$ZIP_PATH" "swarm-analysis-$STAMP" )

SIZE="$(du -h "$ZIP_PATH" | cut -f1)"
COUNT="$(cd "$ROOT" && find . -type f | wc -l | tr -d ' ')"
echo
echo "Done. $COUNT files → $ZIP_PATH ($SIZE)"
